// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-sc6v7UDLwKVN714rcAuuE6fvzEMgnF0',
    appId: '1:724828186533:web:b7431f34cbcf6ba4f6ea4c',
    messagingSenderId: '724828186533',
    projectId: 'signlinggo',
    authDomain: 'signlinggo.firebaseapp.com',
    storageBucket: 'signlinggo.firebasestorage.app',
    measurementId: 'G-GV4N1JMLTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtnZA4ah9ad7__hDiS-CDOTCrrDkEY2SE',
    appId: '1:724828186533:android:df87974ae20409a4f6ea4c',
    messagingSenderId: '724828186533',
    projectId: 'signlinggo',
    storageBucket: 'signlinggo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIA_sTgD4xmv5H5Dl8-aIEG40BVQI8h5g',
    appId: '1:724828186533:ios:923151990801868df6ea4c',
    messagingSenderId: '724828186533',
    projectId: 'signlinggo',
    storageBucket: 'signlinggo.firebasestorage.app',
    androidClientId: '724828186533-67vcgbk4m7fn2s8d84ru56bu2ii2chmb.apps.googleusercontent.com',
    iosClientId: '724828186533-155cbfpgtlp23f5ui7mjk4ggkt0ff2b2.apps.googleusercontent.com',
    iosBundleId: 'com.example.signlinggo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIA_sTgD4xmv5H5Dl8-aIEG40BVQI8h5g',
    appId: '1:724828186533:ios:923151990801868df6ea4c',
    messagingSenderId: '724828186533',
    projectId: 'signlinggo',
    storageBucket: 'signlinggo.firebasestorage.app',
    androidClientId: '724828186533-67vcgbk4m7fn2s8d84ru56bu2ii2chmb.apps.googleusercontent.com',
    iosClientId: '724828186533-155cbfpgtlp23f5ui7mjk4ggkt0ff2b2.apps.googleusercontent.com',
    iosBundleId: 'com.example.signlinggo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-sc6v7UDLwKVN714rcAuuE6fvzEMgnF0',
    appId: '1:724828186533:web:1cd64ef838a920fdf6ea4c',
    messagingSenderId: '724828186533',
    projectId: 'signlinggo',
    authDomain: 'signlinggo.firebaseapp.com',
    storageBucket: 'signlinggo.firebasestorage.app',
    measurementId: 'G-94SS2VVX68',
  );
}
